In [1]:
import pandas as pd 
from sqlalchemy import create_engine

engine = create_engine("postgresql://epigraph:epigraph@localhost:5432/epigraphhub")

In [9]:
def load_df(filename):    
    df = pd.read_csv(filename)

    #del df['Unnamed: 0']
    #df.set_index('date', inplace = True)
    df.date = pd.to_datetime(df.date)
    
    return df

def save_to_database(df, table_name):
    df.to_sql(table_name, engine, schema= 'switzerland', if_exists = 'replace')

In [5]:
df_icu1 = load_df('val_icu_all_cantons1.csv')

df_icu2 = load_df('val_icu_all_cantons2csv')

df_icu = pd.concat([df_icu1, df_icu2])

df_icu

         target       date      lower     median      upper  train_size canton
0     18.500000 2020-04-20  18.346563  18.787829  19.239708         479     AG
1     18.357143 2020-04-21  17.714197  18.197960  18.694935         479     AG
2     17.500000 2020-04-22  17.263470  17.883810  18.526440         479     AG
3     16.714286 2020-04-23  16.200060  16.541189  16.889502         479     AG
4     16.000000 2020-04-24  13.668144  14.179097  14.709151         479     AG
...         ...        ...        ...        ...        ...         ...    ...
5107   8.714286 2022-01-14  12.342990  13.367486  14.477018         480     VS
5108   8.857143 2022-01-15  17.336500  18.640732  20.043082         480     VS
5109   8.928571 2022-01-16  12.690806  13.862003  15.141287         480     VS
5110   9.500000 2022-01-17  15.633572  16.867914  18.199713         480     VS
5111   9.642857 2022-01-18  13.262268  14.148898  15.094802         480     VS

[16596 rows x 7 columns]

In [6]:
save_to_database(df_icu, 'ml_val_icu_all_cantons')

In [12]:
d = pd.read_csv('val_hosp_all_cantons1csv') 

del d['datum']
d

        target        date     lower    median     upper  train_size canton
0     2.428571  2020-03-16  0.791139  0.916226  1.061089         506     FR
1     2.571429  2020-03-17  1.760470  2.214724  2.786188         506     FR
2     3.285714  2020-03-18  1.999811  2.410644  2.905876         506     FR
3     3.714286  2020-03-19  2.696048  3.086232  3.532885         506     FR
4     4.714286  2020-03-20  3.183516  3.629190  4.137256         506     FR
...        ...         ...       ...       ...       ...         ...    ...
5387  2.285714  2022-01-14  2.145425  2.569924  3.078415         506     VS
5388  1.857143  2022-01-15  3.355493  4.405003  5.782773         506     VS
5389  1.571429  2022-01-16  4.565066  5.316203  6.190932         506     VS
5390  0.857143  2022-01-17  1.702217  2.193174  2.825734         506     VS
5391  0.714286  2022-01-18  1.701446  2.032101  2.427014         506     VS

[5392 rows x 7 columns]

In [13]:
d1 = pd.read_csv('val_hosp_all_cantons1csv') 

del d1['datum']

d2 = pd.read_csv('val_hosp_all_cantons2csv') 

del d2['datum']

df_hosp = pd.concat([d1, d2])

df_hosp

,target,date,lower,median,upper,train_size,canton
0,2.428571,2020-03-16,0.791139,0.916226,1.061089,506,FR
1,2.571429,2020-03-17,1.760470,2.214724,2.786188,506,FR
2,3.285714,2020-03-18,1.999811,2.410644,2.905876,506,FR
3,3.714286,2020-03-19,2.696048,3.086232,3.532885,506,FR
4,4.714286,2020-03-20,3.183516,3.629190,4.137256,506,FR
...,...,...,...,...,...,...,...
12127,12.285714,2022-01-14,16.066148,17.161361,18.331234,506,ZH
12128,12.857143,2022-01-15,13.993441,14.847684,15.754075,506,ZH
12129,13.714286,2022-01-16,11.176942,11.670094,12.185004,506,ZH
12130,12.571429,2022-01-17,18.392589,19.331725,20.318814,506,ZH
12131,11.142857,2022-01-18,25.341857,26.801630,28.345490,506,ZH

In [15]:
len(df_hosp.canton.unique())

26

In [17]:
save_to_database(df_hosp, 'ml_val_hosp_all_cantons')